name: "ci"

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
    
jobs:
  puppet-parser-validate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/voxpupuli/openvoxserver:8
      volumes:
        - .:/repo
      options: --cpus 1
    steps:
      - name: Run puppet parser validate
        run: /opt/puppetlabs/bin/puppet parser validate --verbose /repo/
  rspec-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/voxpupuli/voxbox:8
      volumes:
        - .:/repo
      options: --cpus 1
    steps:
      - name: Run rspec tests
        run: spec
