name: "ci"

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
    
jobs:
  puppet-parser-validate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/openvoxproject/openvoxserver
      options: --cpus 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Run puppet parser validate
        run: /opt/puppetlabs/bin/puppet parser validate --verbose ./
  rspec-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/voxpupuli/voxbox:8
      options: --cpus 1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Run rspec tests
        run: rake -f /Rakefile spec
